# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-22 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_details', '0014_animal_animal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourists',
            name='Entryfee',
            field=models.IntegerField(default=200),
        ),
    ]
